/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/offer-control`; params?: Router.UnknownInputParams; } | { pathname: `/offer-details`; params?: Router.UnknownInputParams; } | { pathname: `/personal-information`; params?: Router.UnknownInputParams; } | { pathname: `/product-details`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/add-offer`; params?: Router.UnknownInputParams; } | { pathname: `/admin/add-product`; params?: Router.UnknownInputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit-offer`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit-product`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/likes`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/manage-offers`; params?: Router.UnknownInputParams; } | { pathname: `/admin/manage-products`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/offer-control`; params?: Router.UnknownOutputParams; } | { pathname: `/offer-details`; params?: Router.UnknownOutputParams; } | { pathname: `/personal-information`; params?: Router.UnknownOutputParams; } | { pathname: `/product-details`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/add-offer`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/add-product`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/edit-offer`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/edit-product`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/likes`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/login`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/manage-offers`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/manage-products`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/offer-control${`?${string}` | `#${string}` | ''}` | `/offer-details${`?${string}` | `#${string}` | ''}` | `/personal-information${`?${string}` | `#${string}` | ''}` | `/product-details${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/admin/add-offer${`?${string}` | `#${string}` | ''}` | `/admin/add-product${`?${string}` | `#${string}` | ''}` | `/admin/analytics${`?${string}` | `#${string}` | ''}` | `/admin/edit-offer${`?${string}` | `#${string}` | ''}` | `/admin/edit-product${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/likes${`?${string}` | `#${string}` | ''}` | `/admin/login${`?${string}` | `#${string}` | ''}` | `/admin/manage-offers${`?${string}` | `#${string}` | ''}` | `/admin/manage-products${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/offer-control`; params?: Router.UnknownInputParams; } | { pathname: `/offer-details`; params?: Router.UnknownInputParams; } | { pathname: `/personal-information`; params?: Router.UnknownInputParams; } | { pathname: `/product-details`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/add-offer`; params?: Router.UnknownInputParams; } | { pathname: `/admin/add-product`; params?: Router.UnknownInputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit-offer`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit-product`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/likes`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/manage-offers`; params?: Router.UnknownInputParams; } | { pathname: `/admin/manage-products`; params?: Router.UnknownInputParams; };
    }
  }
}
